# **Practical Lab-8 (Pytorch) Dwarakanath Chandra (8856840)**

### **Using PyTorch:**
#### * **Calculate the dot product between two vectors each of length 3 (1.5 points)**
#### * **Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) (1.5 points)**

In [1]:
# Importing pytorch packages

import torch

#### **Part-A**

In [2]:
# Creating two vectors of length 3 using pytorch

vec1 = torch.tensor([3, 5, 7])
vec2 = torch.tensor([11, 13, 17])
print(vec1)
print(vec2)

tensor([3, 5, 7])
tensor([11, 13, 17])


In [3]:
# Calculating the dot product of vec1 and vec2 using pytorch.

# method-1

dot_prod = vec1.dot(vec2)

print(dot_prod)

tensor(217)


In [4]:
# Calculating the dot product of vec1 and vec2 using pytorch

# method-2

dot_product = torch.dot(vec1, vec2)

print(dot_product)

tensor(217)


#### **Part-B**

In [5]:
# Creating two 2-dimensional matrices of size 2 X 2 using pytorch

mat1 = torch.tensor([[1, 2], [3, 5]])
mat2 = torch.tensor([[8, 13], [21, 34]])

In [6]:
# Performing Matrix multiplication using pytorch

# Method-1

product1 = torch.matmul(mat1, mat2)

print(product1)

tensor([[ 50,  81],
        [129, 209]])


In [7]:
# Performing Matrix multiplication using pytorch

# Method-2

product2 = mat1.matmul(mat2)

print(product2)

tensor([[ 50,  81],
        [129, 209]])


In [8]:
# Performing Matrix multiplication using pytorch

# Method-3

product3 = mat1 @ mat2

print(product3)

tensor([[ 50,  81],
        [129, 209]])


# **Practical Lab-8 (Tensorflow) Dwarakanath Chandra (8856840)**

#### **Using Tensorflow:**
#### * **Calculate the dot product between the same vectors as above (re-define them in Tensorflow) (1.5 points)**
#### * **Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)**

In [1]:
# Importing tensorflow packages

import tensorflow as tf

#### **Part-A**

In [2]:
# Creating two vectors of length 3 using tensorflow

vec1 = tf.constant([3, 5, 7])
vec2 = tf.constant([11, 13, 17])
print(vec1)
print(vec2)

tf.Tensor([3 5 7], shape=(3,), dtype=int32)
tf.Tensor([11 13 17], shape=(3,), dtype=int32)


In [3]:
# Calculating the dot product of vec1 and vec2 using tensorflow

# method-1

dot_prod = tf.tensordot(vec1, vec2, axes = 1)

print(dot_prod)

tf.Tensor(217, shape=(), dtype=int32)


In [4]:
# Calculating the dot product of vec1 and vec2 using tensorflow

# method-2

element_wise_prod = tf.multiply(vec1, vec2)

dot_product = tf.reduce_sum(element_wise_prod)

print(dot_product)

tf.Tensor(217, shape=(), dtype=int32)


#### **Part-B**

In [5]:
# Creating two 2-dimensional matrices of size 2 X 2 using tensorflow

mat1 = tf.constant([[1, 2], [3, 5]])
mat2 = tf.constant([[8, 13], [21, 34]])
print(mat1, mat2)

tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 8 13]
 [21 34]], shape=(2, 2), dtype=int32)


In [6]:
# Performing Matrix multiplication using tensorflow

# Method-1

product1 = tf.matmul(mat1, mat2)

print(product1)

tf.Tensor(
[[ 50  81]
 [129 209]], shape=(2, 2), dtype=int32)


In [7]:
# Performing Matrix multiplication using tensorflow

# Method-2

product2 = mat1 @ mat2

print(product2)

tf.Tensor(
[[ 50  81]
 [129 209]], shape=(2, 2), dtype=int32)
