<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Rokkitt:ital@1&display=swap" rel="stylesheet">

<h1 style="text-align:center;font-family: 'Cinzel', serif;">Practical Lab 8</h1>
<h2 style="text-align:center;font-family: 'Cinzel', serif;">Waseem Raja Shaik</h2>
<h2 style="text-align:center;font-family: 'Cinzel', serif;">Student Id - 8894805</h2>

# Using PyTorch: 
  * Calculate the dot product between two vectors each of length 3 (1.5 points)

In [1]:
import torch

A = torch.tensor([2, 3, 4])
B = torch.tensor([1, 5, 6])

print('Dot Product')
print('one way to do is torch.dot:', torch.dot(A, B))
print('second way to do is torch.sum:', torch.sum(A * B))


Dot Product
one way to do is torch.dot: tensor(41)
second way to do is torch.sum: tensor(41)


  * Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) (1.5 points)

In [2]:
C = torch.tensor([[2, 12], [4, 14]])
D = torch.tensor([[6, 16], [8, 18]])

print("Matrix Multiplication")
print("one way to do is torch.matmul", torch.matmul(C,D))
print("second way to do is torch.mm", torch.mm(C,D))
print("third way to do is @", C@D)

Matrix Multiplication
one way to do is torch.matmul tensor([[108, 248],
        [136, 316]])
second way to do is torch.mm tensor([[108, 248],
        [136, 316]])
third way to do is @ tensor([[108, 248],
        [136, 316]])


# Using Tensorflow: 
  * Calculate the dot product between the same vectors as above (re-define them in Tensorflow) (1.5 points)


In [1]:
import tensorflow as tf
import numpy as np

2023-07-14 15:45:45.778870: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:

A = tf.constant([2, 3, 4])
B = tf.constant([1, 5, 6])

print('Dot Product')
print('one way to do is tf.tensordot:', tf.tensordot(A, B, axes=1))
print('one way to do is tf.reduce_sum(tf.multiply):', tf.reduce_sum(tf.multiply(A, B)))

Dot Product
one way to do is tf.tensordot: tf.Tensor(41, shape=(), dtype=int32)
one way to do is tf.reduce_sum(tf.multiply): tf.Tensor(41, shape=(), dtype=int32)


  * Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)


In [3]:
C = tf.constant([[2, 12], [4, 14]])
D = tf.constant([[6, 16], [8, 18]])

print("Matrix Multiplication")
print("one way to do is tf.matmul", tf.matmul(C,D))
print("second way to do is matmul", tf.linalg.matmul(C,D))
print("third way to do is @", C@D)

Matrix Multiplication
one way to do is tf.matmul tf.Tensor(
[[108 248]
 [136 316]], shape=(2, 2), dtype=int32)
second way to do is matmul tf.Tensor(
[[108 248]
 [136 316]], shape=(2, 2), dtype=int32)
third way to do is @ tf.Tensor(
[[108 248]
 [136 316]], shape=(2, 2), dtype=int32)
