### Name: Dhrushil Dipenkumar Patel
### Student Id: 8862870
### Lab: 8

### Exercise 1:- pyTorch

In [5]:
import torch

### 1. Dot function of vectors

In [6]:
# make avector using torch
X = torch.tensor([13,22,3])
Y =torch.tensor([2,25,1])
X.dot(Y)

tensor(579)

### 2. Matrix multiplication

In [7]:
# matrixmultiplication
X = torch.tensor([[10,12],[13,14]])
Y = torch.tensor([[15,16],[17,18]])
X@Y

tensor([[354, 376],
        [433, 460]])

### Exercise 2:- Tensorflow

In [1]:
import tensorflow as tf

### 1. Dot function of vectors

In [2]:
# Use the same vectors
X = tf.constant([13,22,3])
Y =tf.constant([2,25,1])
tf.tensordot(X,Y,axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=579>

In [3]:
# Matrixmultiplication of 2*2 matrix
X = tf.constant([[10,12],[13,14]])
Y = tf.constant([[15,16],[17,18]])
tf.matmul(X,Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[354, 376],
       [433, 460]])>