# lab 8 
## part 1 : pyTorch 

In [1]:
import torch

1. Dot function of vectors

In [2]:
# make avector using torch of 3 elements
a = torch.tensor([30,2,33])
b=torch.tensor([42,53,61])
a.dot(b)


tensor(3379)

2. matrix multiplication of 2*2 matrix

In [3]:
# matrixmultiplication of 2*2 matrix
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
a@b

tensor([[19, 22],
        [43, 50]])

## part 2: tensorflow 

In [1]:
import tensorflow as tf

1. dot functioin on vector

In [2]:
# use the same vectors as in the dot product using tf
a = tf.constant([30,2,33])
b=tf.constant([42,53,61])
tf.tensordot(a,b,axes=1)



<tf.Tensor: shape=(), dtype=int32, numpy=3379>

In [3]:
#matrixmultiplication of 2*2 matrix using tf
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>