# _**<font color= 'purple'> <u>Lab 1 – Basic NumPy Operations </u></font>**_

## _**<font color= 'salmon'><U> Part -A- </U> </font>**_

>1.Create a Notebook to demonstrate NumPy Operations. <br>
>2.Create an array that starts from the integer 1, ends at 20, incremented by 3.


In [1]:
import numpy as np 
array1 = np.arange(1, 21, 3)
print("Array 1:", array1)

Array 1: [ 1  4  7 10 13 16 19]


>3.Create a new array of shape 3 with random numbers between 0 and 1.

In [2]:
array2 = np.random.random((3))
print("Array 2:", array2)

Array 2: [0.35806859 0.41197546 0.2063526 ]


>4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: <br>
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [3]:
Two_D_array = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("2-D array:\n {}".format(Two_D_array))

# Slice the 2D array to get the first two rows
First_2_rows =Two_D_array[:2, :]
print("First two rows:\n {}".format(First_2_rows))    

# Slice the 2D array to get the last two rows
Last_2_rows = Two_D_array[1:, :]
print("Last two rows:\n", Last_2_rows)

2-D array:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]
First two rows:
 [[10 20 45]
 [30 12 16]]
Last two rows:
 [[30 12 16]
 [42 17 56]]


>5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays. 

In [4]:
# Create input array 1 & 2
in_arr1 = np.array([[7, 2], [9, 4]])
print ("1st Input array : \n", in_arr1) 
in_arr2 = np.array([[5, 6], [18, 8]])
print ("2nd Input array : \n", in_arr2) 
# Stack the elements vertically
Vertical_stack = np.vstack((in_arr1, in_arr2))
print("Vertical Stack:",Vertical_stack)

# Stack the elements horizontally
Horizontal_stack = np.hstack((in_arr1, in_arr2))
print("Horizontal Stack:",Horizontal_stack)

# Split the arrays into smaller arrays
split_in_arr1 = np.split(in_arr1, 2)
split_in_arr2 = np.split(in_arr2, 2)
print("Split Array 1:", split_in_arr1)
print("Split Array 2:",split_in_arr2 )

1st Input array : 
 [[7 2]
 [9 4]]
2nd Input array : 
 [[ 5  6]
 [18  8]]
Vertical Stack: [[ 7  2]
 [ 9  4]
 [ 5  6]
 [18  8]]
Horizontal Stack: [[ 7  2  5  6]
 [ 9  4 18  8]]
Split Array 1: [array([[7, 2]]), array([[9, 4]])]
Split Array 2: [array([[5, 6]]), array([[18,  8]])]


> 6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),Is it possible to multiply these matrices? Demonstrate the case when it is not possible to.

In [5]:
# 6. Create matrices X and Y
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

if X.shape[1] == Y.shape[0]:
    result = np.dot(X, Y)
    print("Matrix multiplication result:\n", result)
else:
    print("Matrix multiplication is not possible due to incompatible dimensions.") 

Matrix multiplication result:
 [[70 28]
 [70 30]
 [60 26]]


> <font color = 'orange'> **To perform matrix multiplication, the number of columns in the first matrix (X) must be equal to the number of rows in the second matrix (Y). In this case, X has 3 columns while Y has 3 rows, which does satisfy the condition for matrix multiplication.
Hence, in this example, it is possible to multiply matrices X and Y due to the compatible dimensions.** </font>

> 7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.**_ <br> Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [7]:
# shape (= length of each dimension)  # reshape() to convert the shape # ndim get the number of dimensions of a NumPy array as an integer 
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])
shape_x = x.shape
num_dim_x = x.ndim
print("Shape of vector x:\n", shape_x)
print("Number of dimensions of vector x:\n", num_dim_x)    
 
# Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).
# New axis added 'columns ' to the data 
reshaped_y = y.reshape((3, 1))
num_dim_reshaped_y= reshaped_y.ndim
reshaped_x = x.reshape((3, 1))
num_dim_reshaped_x = reshaped_x.ndim

print("Number of dimensions after reshaping x:{}" .format(num_dim_reshaped_x))
print("Number of dimensions after reshaping y:{}".format(num_dim_reshaped_y))

Shape of vector x:
 (3,)
Number of dimensions of vector x:
 1
Number of dimensions after reshaping x:2
Number of dimensions after reshaping y:2


 >8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.
   

> Broadcasting in NumPy allows arrays of different shapes to be used in arithmetic operations. However, with broadcasting, arrays with different shapes can be used, and the operations are automatically applied to corresponding elements. This allows for seamless computations even when the shapes of the arrays do not match exactly.
When working with arrays of different dimensions in NumPy, direct element-wise operations may not be possible. However, NumPy provides the capability of broadcasting, which allows for operations on arrays with dissimilar shapes. Broadcasting involves adjusting the smaller array to match the shape of the larger array so that element-wise operations can be performed. <br>

In [8]:
Matrix = np.array([[2, 6, 3],
                   [8, 5, 4],
                   [1, 7, 9]])

# Perform subtraction with a scalar
subtraction_op = Matrix - 3

# Perform multiplication with a scalar
multiplication_op = Matrix * 2
print("Original matrix:\n", Matrix)
print("\nResult after subtraction:\n", subtraction_op)
print("\nResult after multiplication:\n", multiplication_op)

Original matrix:
 [[2 6 3]
 [8 5 4]
 [1 7 9]]

Result after subtraction:
 [[-1  3  0]
 [ 5  2  1]
 [-2  4  6]]

Result after multiplication:
 [[ 4 12  6]
 [16 10  8]
 [ 2 14 18]]


 ## _**<font color= 'salmon'><U> Part -B- </U> </font>**_

>1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. <br>
> <u> <b>First System </b> </u> <br>
> 2x1+3x2-4x3=6,x1-4x2=8

In [9]:
# Coefficient matrix
A = np.array([[2, 3, -4],
              [1, -4, 0]])

# Constant matrix
B = np.array([6, 8])

print("The shape of A matrix is: \n", A.shape)
print("The shape of B matrix is: \n", B.shape)

The shape of A matrix is: 
 (2, 3)
The shape of B matrix is: 
 (2,)


>The order of resulting matrix  ~ (2,3)*(3,1) ~ will be the first number by the forth number (2,1) Not possible in our case we suppose to have (3,1) instead.
Furthermore, Since the shape of matrix A is 2x3 (non-square), we cannot calculate the determinant and determine if it is non-zero. Without a non-zero determinant, we cannot calculate the inverse of matrix A and find a unique solution to the system of equations. Therefore, it is not possible to find the solution matrix (x1, x2, x3)using matrix operations in this case.

> <u> <b>Second System </b> </u> <br>
>  3y1-4y2+5y3=10,-y1+2y2-4y3=8


In [10]:
# Coefficient matrix
Y = np.array([[3,-4,5],[-1,2,-4]])

# Constant matrix
Z = np.array([10,8])

print("The shape of Y matrix is: \n", Y.shape)
print("The shape of Z matrix is: \n", Z.shape)

The shape of Y matrix is: 
 (2, 3)
The shape of Z matrix is: 
 (2,)


>Same reasoning, the order of resulting Matrix is inaccurate "(2,3)*(3,1) ==> (2,1)". Moreover, we cannot calculate the determinant of Matrix Y.

>Therefore, it is not possible to find the solution matrix [y1, y2, y3] using matrix operations in this case.