##  <font color = '#1589FF'> <i> <b> <u> Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow </u> </b> </i>

####  <font color = '#36454F'> <i> <b> <u> - Using PyTorch: </i> </b></u> </font>  <br>
####   <font color = '#1589FF'> <i> <b> <u> Calculate the dot product between two vectors each of length 3  </u> </b> </i> </font>

In [1]:
import torch

# Define the vectors
vect1 = torch.tensor([3, 5, 7])
vect2 = torch.tensor([1, 3, 8])
print(vect1, "\n\n", vect2)


tensor([3, 5, 7]) 

 tensor([1, 3, 8])


In [7]:
#  Calculate the dot product
dot_product = torch.dot(vect1, vect2)
print("Dot product using PyTorch:", dot_product)

Dot product using PyTorch: tensor(74)


####  <font color = '#1589FF'> <i> <b> <u> 
#### Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)  </u> </b> </i> </font>


In [4]:
# Define the matrices
matrx1 = torch.tensor([[1, 2], [3, 4]])
matrx2 = torch.tensor([[5, 6], [7, 8]])
# Calculate the matrix multiplication
matrix_product = torch.matmul(matrx1, matrx2)
print("Matrix multiplication using PyTorch:")
print(matrix_product)

Matrix multiplication using PyTorch:
tensor([[19, 22],
        [43, 50]])


####  <font color = '#36454F'> <i> <b> <u> Using Tensorflow: </i> </b></u> </font>  <br>
####   <font color = '#1589FF'> <i> <b> <u> Calculate the dot product between the same vectors as above (re-define them in Tensorflow)  </u> </b> </i> </font>

In [1]:
import tensorflow as tf

# Define the vectors
vector1 = tf.constant([3, 5, 7])
vector2 = tf.constant([1, 3, 8])

# Calculate the dot product
dot_product = tf.tensordot(vector1, vector2, axes=1)

print("Dot product using TensorFlow:", dot_product)



Dot product using TensorFlow: tf.Tensor(74, shape=(), dtype=int32)


In [2]:
# Define the matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
# Calculate the matrix multiplication
matrix_product = tf.matmul(matrix1, matrix2)
print("Matrix multiplication using TensorFlow:")
print(matrix_product)

Matrix multiplication using TensorFlow:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
