In [15]:
import tensorflow as tf

* Calculate the dot product between the same vectors as above (re-define them in Tensorflow)

In [16]:
a= tf.constant([2,4,6])
b= tf.constant([8,10,12])
c= tf.tensordot(a,b,axes=1)
print(f'A : {a}')
print(f'B : {b}')
print(f'A.B :{c}')
c

A : [2 4 6]
B : [ 8 10 12]
A.B :128


<tf.Tensor: shape=(), dtype=int32, numpy=128>

* Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) 

In [17]:
x= tf.constant([[2,4],[6,8]])
y= tf.constant([[10,12],[14,16]])
z= tf.matmul(x,y)
print(f'X : {x}')
print(f'Y : {y}')
print(f'X*Y : {z}')
z

X : [[2 4]
 [6 8]]
Y : [[10 12]
 [14 16]]
X*Y : [[ 76  88]
 [172 200]]


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76,  88],
       [172, 200]])>