In [3]:
def add(x):
    return x+1
# representing same function as a lamda function
x = 1
print(add(x))
addOne = lambda x:x+1
print(addOne(x))

2
2


In [4]:
multiply = lambda x,y: x*y
print(multiply(2,2))

4


In [7]:
def fullName(firstName, lastName):
    name = firstName + ' , ' + lastName
    return f'Your full name is {name}'

fullNameLambda = lambda firstName, lastName:'Your full name'+ \
f' is {firstName} , {lastName}'
fullNameLambda("Islam","Mahmoud")

'Your full name is Islam , Mahmoud'

In [8]:
import numpy as np
np.__version__

'1.19.5'

In [11]:
# creating simple array from list values
pythonList = [1,2,3]
numpyArray1 = np.array(pythonList)
# creating a numpy array- range of values
# arange takes start inclusive, stop exclusive, and steps taken
# default steps is 1
numpyArray2 = np.arange(1,10,2)
numpyArray2

array([1, 3, 5, 7, 9])

In [14]:
numpyFirst2D = np.array([[1,2,3]
                        ,[5,6,7]])
# checking how many dimensions do we have
numpyFirst2D.ndim

2

In [23]:
# defining array and setting it to specific dimensions
print(np.array(pythonList, ndmin=5))
# accessing element in numpy array 
print(numpyArray1[0])
# accessing nd-arrays 
print(numpyFirst2D[1,1]) # can also be written as numpyFirst2[1][1]
# negative indexing
print(numpyArray2[-1])

[[[[[1 2 3]]]]]
1
2
9


In [30]:
numpyArray2

array([1, 3, 5, 7, 9])

In [33]:
# extracts numpy elements from index 1 to index 3 (index 4 excluded)
numpyArray2[1:4] # takes start:end:step, can also be written as:
# numpyArray2[1:-1]
numpyArray2[::2] # if start and end are not written, step is written
# then all array will be shown by taking step of 2

array([1, 5, 9])

In [50]:
numpyArray2 = np.arange(1,10,2)
# incorrect way of copying
arr3= numpyArray2.view()

arr4 = numpyArray2.copy()

arr3[0]=0
print(arr3, numpyArray2)
# correct way
arr4[0]=2
print(arr4, numpyArray2)

[0 3 5 7 9] [0 3 5 7 9]
[2 3 5 7 9] [0 3 5 7 9]


In [51]:
print(arr3.base, arr4.base, numpyArray2.base)

[0 3 5 7 9] None None


In [52]:
# shape returns the array shape as tuple
numpyArray2.shape


(5,)

In [57]:
# reshapes the array
numpyFirst2D.reshape((3,2))
# iterating without bothering the dimensions value
for element in np.nditer(numpyFirst2D):
    print(element)

1
2
3
1
2
3


In [62]:
print(arr4, numpyArray1)
arr5 = np.concatenate((arr4,numpyArray1))
arr5

[2 3 5 7 9] [1 2 3]


array([2, 3, 5, 7, 9, 1, 2, 3])

In [69]:
numpyFirst2D.shape

(2, 3)

In [74]:
# adding 1d to a 2d array, needs to be reshaped first to match
# the dimensions
numpyArray1Reshaped = numpyArray1.reshape(-1,3)
arr6 = np.concatenate((numpyFirst2D, numpyArray1Reshaped))
arr6


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [93]:
# returns the index where the condition is True
np.where(numpyArray1!=2)

(array([0, 2], dtype=int64),)

In [92]:
numpyArrayUnsorted = np.array([10,2,3,7,12,8,22,1])
# sorting
np.sort(numpyArrayUnsorted)
# reverse sorting
np.sort(numpyArrayUnsorted)[::-1]

array([22, 12, 10,  8,  7,  3,  2,  1])

In [94]:
# filtering array
filterX = np.where(numpyArray1!=2)
numpyArray1[filterX]

array([1, 3])

In [99]:
from numpy import random
# setting a seed so every run I get the same value
random.seed(10)
# returns float from 0-1 of size 10
random.rand(10)
# returns int from 10 to 15 (16 excluded) of size 20
random.randint(10,16,20)

array([14, 13, 10, 14, 13, 10, 13, 12, 11, 10, 14, 11, 13, 15, 15, 15, 13,
       11, 15, 14])

In [103]:
# numpy array of zeros
np.zeros((10,10))
# numpy array of ones
np.ones((10,10))
# numpy full array of specified value (here nan)
np.full((10,10),np.nan)

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])