Calculate the dot product between two vectors each of length 3 (1.5 points)

In [1]:
import torch

# Define the vectors using PyTorch
vector1 = torch.tensor([3.14, 1.59, 2.71], dtype=torch.float32)
vector2 = torch.tensor([2.23, 0.97, 1.41], dtype=torch.float32)

# Method 1: Using torch.dot()
dot_product1 = torch.dot(vector1, vector2)
print("Dot product (Method 1):", dot_product1.item())

# Method 2: Using element-wise multiplication and sum
dot_product2 = torch.sum(vector1 * vector2)
print("Dot product (Method 2):", dot_product2.item())

# Method 3: Using torch.matmul()
dot_product3 = torch.matmul(vector1.unsqueeze(0), vector2.unsqueeze(1))
print("Dot product (Method 3):", dot_product3.item())

# Method 4: Using torch.einsum()
dot_product4 = torch.einsum("i,i->", vector1, vector2)
print("Dot product (Method 4):", dot_product4.item())

# Method 5: Using torch.nn.functional.cosine_similarity()
normalized_vector1 = torch.nn.functional.normalize(vector1, dim=0)
normalized_vector2 = torch.nn.functional.normalize(vector2, dim=0)
dot_product5 = torch.nn.functional.cosine_similarity(normalized_vector1, normalized_vector2, dim=0)
print("Dot product (Method 5):", dot_product5.item())


Dot product (Method 1): 12.3656005859375
Dot product (Method 2): 12.3656005859375
Dot product (Method 3): 12.3656005859375
Dot product (Method 4): 12.3656005859375
Dot product (Method 5): 0.9902983903884888


Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) (1.5 points)

In [2]:
# Define the matrices using PyTorch
matrix1 = torch.tensor([[51.64, 80.72],
                        [23.15, 42.37]], dtype=torch.float32)

matrix2 = torch.tensor([[15.25, 67.93],
                        [81.84, 92.56]], dtype=torch.float32)

# Method 1: Using torch.matmul()
matrix_mult1 = torch.matmul(matrix1, matrix2)
print("Matrix multiplication (Method 1):")
print(matrix_mult1)

# Method 2: Using torch.mm()
matrix_mult2 = torch.mm(matrix1, matrix2)
print("Matrix multiplication (Method 2):")
print(matrix_mult2)

# Method 3: Using @ operator
matrix_mult3 = matrix1 @ matrix2
print("Matrix multiplication (Method 3):")
print(matrix_mult3)

# Method 4: Using torch.einsum()
matrix_mult4 = torch.einsum('ij,jk->ik', matrix1, matrix2)
print("Matrix multiplication (Method 4):")
print(matrix_mult4)


Matrix multiplication (Method 1):
tensor([[ 7393.6348, 10979.3486],
        [ 3820.5981,  5494.3467]])
Matrix multiplication (Method 2):
tensor([[ 7393.6348, 10979.3486],
        [ 3820.5981,  5494.3467]])
Matrix multiplication (Method 3):
tensor([[ 7393.6348, 10979.3486],
        [ 3820.5981,  5494.3467]])
Matrix multiplication (Method 4):
tensor([[ 7393.6348, 10979.3486],
        [ 3820.5981,  5494.3467]])


Method 1: Directly calculating the dot product of the two vectors using the torch.dot() method.

Method 2: Using the * operator to multiply the vectors element-by-element, using torch.sum() to add the resulting tensor.

Method 3: Matrix multiplication between the vectors using the torch.matmul() method. The output is a 1x1 tensor that represents the dot product since the vectors are rearranged into a row vector (vector1.unsqueeze(0)) and a column vector.

Method 4: Compute the dot product directly by summing the element-wise products of the vectors using torch.einsum() and the given equation "i,i->".

Method 5: Utilising torch.nn.functional.cosine_similarity() after torch.nn.functional.normalize() has normalised the vectors. When the vectors are unit normalised, this approach computes the cosine similarity between them, which is identical to the dot product.

Method 1.Using the torch.matmul() function directly.

Method 2: Applying the torch.mm() function, which is intended for 2D matrix multiplication.

Method 3: Matrix multiplication is carried out through the @ operator.

Method 4: Direct matrix multiplication computation by using torch.einsum() and a contraction operation.

Using Tensorflow:

Calculate the dot product between the same vectors as above (re-define them in Tensorflow) (1.5 points)

In [2]:
import tensorflow as tf

# Define the vectors using TensorFlow
vector1 = tf.constant([3.14, 1.59, 2.71], dtype=tf.float32)
vector2 = tf.constant([2.23, 0.97, 1.41], dtype=tf.float32)

# Method 1: Using tf.tensordot()
dot_product1 = tf.tensordot(vector1, vector2, axes=1)
print("Dot product (Method 1):", dot_product1.numpy())

# Method 2: Using tf.reduce_sum() and tf.multiply()
dot_product2 = tf.reduce_sum(tf.multiply(vector1, vector2))
print("Dot product (Method 2):", dot_product2.numpy())

# Method 3: Using tf.einsum()
dot_product3 = tf.einsum("i,i->", vector1, vector2)
print("Dot product (Method 3):", dot_product3.numpy())

# Method 4: Using tf.math.reduce_sum() and tf.math.multiply()
dot_product4 = tf.math.reduce_sum(tf.math.multiply(vector1, vector2))
print("Dot product (Method 4):", dot_product4.numpy())

# Method 5: Using tf.linalg.matmul() with matrix reshaping
reshaped_vector1 = tf.reshape(vector1, [3, 1])
reshaped_vector2 = tf.reshape(vector2, [1, 3])
dot_product5 = tf.linalg.matmul(reshaped_vector1, reshaped_vector2)
print("Dot product (Method 5):", dot_product5.numpy())


Dot product (Method 1): 12.365601
Dot product (Method 2): 12.365601
Dot product (Method 3): 12.365601
Dot product (Method 4): 12.365601
Dot product (Method 5): [[7.0022    3.0458002 4.4274   ]
 [3.5457    1.5423001 2.2419   ]
 [6.0433    2.6287    3.8211   ]]


Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)

In [4]:
# Define the matrices using TensorFlow
matrix1 = tf.constant([[51.64, 80.72],
                       [23.15, 42.37]], dtype=tf.float32)

matrix2 = tf.constant([[15.25, 67.93],
                       [81.84, 92.56]], dtype=tf.float32)

# Method 1: Using tf.matmul()
matrix_mult1 = tf.matmul(matrix1, matrix2)
print("Matrix multiplication (Method 1):")
print(matrix_mult1.numpy())

# Method 2: Using tf.linalg.matmul()
matrix_mult2 = tf.linalg.matmul(matrix1, matrix2)
print("Matrix multiplication (Method 2):")
print(matrix_mult2.numpy())

# Method 3: Using tf.tensordot()
matrix_mult3 = tf.tensordot(matrix1, matrix2, axes=1)
print("Matrix multiplication (Method 3):")
print(matrix_mult3.numpy())

# Method 4: Using tf.reduce_sum() and tf.multiply()
matrix_mult4 = tf.reduce_sum(tf.multiply(tf.expand_dims(matrix1, axis=1), tf.expand_dims(matrix2, axis=0)), axis=2)
print("Matrix multiplication (Method 4):")
print(matrix_mult4.numpy())


Matrix multiplication (Method 1):
[[ 7393.635  10979.349 ]
 [ 3820.5981  5494.3467]]
Matrix multiplication (Method 2):
[[ 7393.635  10979.349 ]
 [ 3820.5981  5494.3467]]
Matrix multiplication (Method 3):
[[ 7393.635  10979.349 ]
 [ 3820.5981  5494.3467]]
Matrix multiplication (Method 4):
[[ 6270.8193 11697.66  ]
 [ 3231.2317  5816.363 ]]


Method 1: By setting axes=1 and using the tf.tensordot() function to calculate the dot product of the two vectors directly.

Method 2: Element-wise multiplying the vectors with tf.reduce_sum() and tf.multiply(), then summing the resulting tensor to get the dot product.

Method 3: Using the given equation "i,i->" and tf.einsum() to calculate the dot product by adding the element-wise products of the vectors directly.

Method 4: Element-wise multiplying the vectors with tf.math.reduce_sum() and tf.math.multiply(), then summing the resulting tensor to get the dot product.

Method 5: Converting the vectors into a 2D matrix using tf.linalg.matmul(). Both reshaped_vector1 and reshaped_vector2 are transformed into column vectors ([3, 1]) and row vectors ([1, 3]), respectively. After that, matrix multiplication is carried out.

Method 1: Directly calculating the matrix multiplication of matrices 1 and 2 using the tf.matmul() function.

Method 2: Calculate the matrix multiplication of matrices 1 and 2 using the tf.linalg.matmul() function. This technique can handle more complex matrix operations and is the same as tf.matmul().

Method 3: Matrix multiplication using the tf.tensordot() method with axes set to 1.

Method 4: Compute the matrix multiplication by element-wise multiplication and summing the resulting tensor using tf.reduce_sum() and tf.multiply(). To simplify element-wise multiplication, more dimensions are added to matrix1 and matrix2 using tf.expand_dims().