## Tensorflow

In [14]:
import tensorflow as tf

In [15]:
x = tf.constant([1., 2., 10.])
y = tf.constant([-3., 6., -5.])

For dot product of two vectors, , calculate element-wise multiplication first and get reduce sum of resulted matrix.

In [16]:
tf.reduce_sum(tf.multiply(x, y))

<tf.Tensor: shape=(), dtype=float32, numpy=-41.0>

Matrix multiplication of two 2-dimensional matrices

In [17]:
a = tf.constant([[4, 8], [20, 15]])
b = tf.constant([[9, 2], [12, 23]])
print(a.shape)
print(b.shape)

(2, 2)
(2, 2)


In [18]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[132, 192],
       [360, 385]])>