#### ARJUN KC(8773456)

In [1]:
try:
    import torch
    print(f'Tensor: {torch.tensor([10, 10])}')
    print(f'PyTorch version: {torch.__version__}')    
    print('Succeeded')
except:
    print("Didn't succeed")

Tensor: tensor([10, 10])
PyTorch version: 2.0.0+cpu
Succeeded


#### Using Pytorch

In [3]:
import sys
import torch

Using PyTorch: 
  * Calculate the dot product between two vectors each of length 3 

In [10]:
v1 = torch.tensor([7,8,9])  #defining the first vector
v2 = torch.tensor([9,8,7])  #degfinig the second vector


In [11]:
dot_prd = torch.dot(v1,v2)

In [17]:
dot_prd  #showing the output with tensor object and value

tensor(190)

In [16]:
print(f'the output of the dot product between two vectors each of length 3 is {dot_prd}')

the output of the dot product between two vectors each of length 3 is 190


In [18]:
dot_prd.item()  #showing the output by extracting the scalar value from tensor

190

 Using PyTorch: 
  *   Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) 

In [50]:
mat1 = torch.tensor([[2,3],[4,5]]) #defining the first 2-dim matrix
mat2 = torch.tensor([[6,7,],[8,9]])#definig the second 2-dim  matrix

Note: in pytorch we can use @  or matmul for matrix multiplication

In [51]:
mat = torch.matmul(mat1,mat2)  #printing using matmul

In [52]:
mat  #printing the ouput with the tensor object and value 

tensor([[36, 41],
        [64, 73]])

In [53]:
mat = mat1 @ mat2  #using the @ 

In [54]:
print(mat)
print("Dimension:",mat.dim())
print("Shape:",mat.shape)


tensor([[36, 41],
        [64, 73]])
Dimension: 2
Shape: torch.Size([2, 2])


In [55]:
print(f'the matrx multiplication of two 2-dimension matrix with each size of (2,2) is :{mat}')

the matrx multiplication of two 2-dimension matrix with each size of (2,2) is :tensor([[36, 41],
        [64, 73]])


#### Using Tensorflow

In [1]:
import tensorflow as tf
import numpy as np

Using Tensorflow: 
  * Calculate the dot product between the same vectors as above (re-define them in Tensorflow)

In [2]:
v1 = tf.constant([7,8,9])
v2 = tf.constant([9,8,7])

In [11]:
dot_prd = tf.tensordot(v1,v2,axes=1)

In [17]:
dot_prd.numpy()  #we use numpy to get value from tensorflow

190

In [18]:
print(f'the dot product betwwen the two vector of each lenght of 3 is {dot_prd.numpy()}')

the dot product betwwen the two vector of each lenght of 3 is 190


Using Tensorflow:
* Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow)

In [52]:
mat1 = tf.constant([[2.,3.],[4.,5.]]) #defining the first 2-dim matrix
mat2 = tf.constant([[6.,7.],[8.,9.]]) #defining the second 2-dim matrix

In [64]:
mat = tf.matmul(mat1,mat2)

In [63]:
print(mat) #printing the value with tensor


tf.Tensor(
[[36. 41.]
 [64. 73.]], shape=(2, 2), dtype=float32)


#### or

In [67]:
print(mat.numpy())  #value is extracted using numpy

[[36. 41.]
 [64. 73.]]


In [68]:
print(f'the matrx multiplication of two 2-dimension matrix with each size of (2,2) is :{mat.numpy()}')

the matrx multiplication of two 2-dimension matrix with each size of (2,2) is :[[36. 41.]
 [64. 73.]]
