# Part-I

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import numpy as np


In [2]:
# Load the Iris dataset
df = load_iris()

In [10]:
X=df.data
y=df.target

In [6]:
X[:5]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [7]:
y[:5]

array([0, 0, 0, 0, 0])

In [11]:
unique_1 = np.unique(y, return_counts=True)
unique_1

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

labels

In [12]:
import numpy as np
y_binary = (y == 2)
y_binary = y_binary.astype(int)

making it  into a 2 class classification

In [16]:
print(y_binary)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


In [17]:
unique_1 = np.unique(y, return_counts=True)
unique_1

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

In [18]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.2)

In [19]:
# Training a logistic regression model
model = LogisticRegression()

In [20]:
model.fit(X_train, y_train)

LogisticRegression()

In [21]:
# test predictions
y_pred = model.predict(X_test)

In [23]:
#  accuracy 
accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0

100% accuracy

In [24]:
# Calculate confusion matrix
confusion_matrix_ = confusion_matrix(y_test, y_pred)


In [25]:
confusion_matrix_

array([[19,  0],
       [ 0, 11]], dtype=int64)

## part 2

Interpretations
The model's proficiency can be evaluated by the accuracy score acquired from the test data, which signifies the ratio of samples that were correctly predicted.
The coefficients of the logistic regression model can provide us with an understanding of the importance of each feature in the classification procedure. If a coefficient is positive, it means that an increase in the corresponding feature value will increase the odds of the sample being classified as "virginica," while a negative coefficient suggests the opposite. By examining these coefficients, we can determine which features play a significant role in the classification decision.
Given that the accuracy is 1, it suggests the presence of overfitting.
Incorrect Predictions
Observing the accuracy score reveals that the model exhibits a 100% accuracy rate, which may not hold true in reality. However, according to the model, no prediction for any data point is incorrect.

Common Traits
Examine Feature Values: Investigate the feature values of inaccurately classified instances to uncover any shared characteristics or patterns. Scrutinize the features for certain ranges, combinations, or relationships that might lead to incorrect classifications. Inspect if there are samples with similar petal lengths but varying sepal widths, or if a certain feature range experiences more misclassifications.

Construct visual representations for the incorrectly classified instances and their feature distributions, like scatter plots or histograms. Individually plotting the inaccurately classified samples for each class might highlight any overlap areas or instances near the decision boundary. These visual aids can assist the model in pinpointing potential areas of confusion.

Evaluation
Overfitting: Overfitting arises when a model performs exceptionally well on the training data but does not extend this performance to unseen data. The model might have learned the training data too well, even memorizing noise and outliers, which leads to perfect accuracy. However, its performance on new data could be less than ideal. Overfitting can be described with phrases like:
Over-optimization: The model has fine-tuned itself excessively to the training data, which leads to perfect accuracy.

Data Memorization: The model has virtually remembered the training data, including its anomalies or noise.

Lack of Generalization: The model might not extrapolate well to unseen data, rendering its perfect accuracy untrustworthy for real-world scenarios.

Excellence: On the contrary, if the model achieves 100% accuracy and can still perform well on new, unseen data, it demonstrates excellence. The model has successfully identified the underlying patterns and relationships in the data without overfitting. Phrases to describe excellence include:
Exceptional: The model's flawless accuracy showcases its extraordinary performance and capability to understand the complexity of the dataset.

Outstanding: The model's accuracy is impressive, reflecting its superior performance in accurately categorizing instances.