# Lab 6 - Logistic Regression

1. Using SciKit-Learn, train a logistic regression model on the Iris dataset. Use all four features. Define only 2 labels: virginica and non-virginica. See the logistic regression notebook presented in class for a demonstration on how to set up these labels (3 points).

2. Provide insights about the model prediction. This is an open-ended part. But you can look into questions such as in which data instances is the model wrong? are there any shared properties for these cases? and _how is the model doing, across a set of performance metrics such as accuracy and confusion metric. (3 points)

In [52]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score,confusion_matrix,recall_score

import numpy as np
import pandas as pd

In [19]:
# Load the Iris dataset
iris = load_iris(as_frame=True) 


In [20]:
type(iris)

sklearn.utils._bunch.Bunch

In [21]:
list(iris)  # show the keys of the Bunch dictionary

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [22]:
# print types of all the keys
for key in iris.keys():
    print(key, type(iris[key]))

data <class 'pandas.core.frame.DataFrame'>
target <class 'pandas.core.series.Series'>
frame <class 'pandas.core.frame.DataFrame'>
target_names <class 'numpy.ndarray'>
DESCR <class 'str'>
feature_names <class 'list'>
filename <class 'str'>
data_module <class 'str'>


In [23]:
iris.data.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [25]:
iris.target.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: target, dtype: int32

In [26]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [27]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [30]:
X = iris.data
y = iris.target

In [33]:
# Define only 2 labels: virginica and non-virginica.
# feauture "setosa" and "versicolor" as one class, and "virginica" as another class
y[y != 2] = 0  # Set labels other than "virginica" as 0 (so iris setosa and versicolor is set to non virginica class (0))
y[y == 2] = 1  # Set "virginica" labels as 1

Fitting the Model

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creating model
model = LogisticRegression()
# Fitting the model
model.fit(X_train, y_train)


LogisticRegression()

In [39]:
# prediction
y_pred = model.predict(X_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0])

**Cross Validation**

In [48]:
# Perfoming cross-validation to check models perfomance across different folds

cv_score = cross_val_score(model, X_train, y_train, cv=5)
cv_score


array([1.        , 0.95833333, 0.875     , 0.95833333, 0.95833333])

The CV on the 1st fold shows 100% accuracy whereas other folds shows 95% except for the 3rd fold with 87%. 

In [47]:
print("Average accuracy : ", np.mean(cv_score))

Average accuracy :  0.95


Accuracy score is quite good too with 95%

**Confusion Matrix**

In [49]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[19,  0],
       [ 0, 11]], dtype=int64)

## There is no false positive and false negative. It shows the model has Perfect accuracy.

**Precision & Recall**

In [50]:
prec_score = precision_score(y_test, y_pred)
rec_score = recall_score(y_test, y_pred)

print(f"Precision Score : {prec_score}")
print(f"Recall Score : {rec_score}")

Precision Score : 1.0
Recall Score : 1.0


In [53]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Conclusions: It is clear from the metric that the model accurately predicts every metric. It seems that the model is overfitting. 
I think its because the data is very less.

Iris setosa and versicolor were converted to the non-virginica class for our dataset, resulting in an imbalanced dependent variable. Since one class is far more common than the other, the model can achieve high accuracy by consistently predicting the dominant class.