## Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow

Tenzin Yangzom - 8896839

**Using PyTorch:**
- Calculate the dot product between two vectors each of length 3 (1.5 points)
- Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) (1.5 points)

**Using Tensorflow:**
- Calculate the dot product between the same vectors as above (re-define them in Tensorflow) (1.5 points)
- Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)

# **PyTorch**

In [1]:
import sys
import torch
import helpers as h

#### Dot Product between two vectors each of length 3

$\textbf{u} \cdot \textbf{v} = \sum_i{\textbf{u}_i \times \textbf{v}_i}$

In [13]:
# initializing two rank-2 tensors
x = torch.tensor([1.,2.,3.])
y = torch.tensor([2.,3.,4.])

print(f'x: {x}')
print(f'y: {y}')

x: tensor([1., 2., 3.])
y: tensor([2., 3., 4.])


In [14]:
x.dot(y)

tensor(20.)

In [15]:
y.dot(x)

tensor(20.)

OR

In [16]:
torch.dot(x,y)

tensor(20.)

In [17]:
h.print_tensor_info(x)

tensor([1., 2., 3.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (3,)


#### Matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

In [18]:
x = torch.tensor([[1., 2.],[3., 4.]])
y = torch.tensor([[5., 6.],[7., 8.]])

print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [19]:
print(torch.matmul(x, y))

tensor([[19., 22.],
        [43., 50.]])


In [20]:
x.matmul(y)

tensor([[19., 22.],
        [43., 50.]])

@ is an alias of `matmul`


In [22]:
x@y

tensor([[19., 22.],
        [43., 50.]])

# **Tensorflow**

#### Dot product between two vectors each of length 3

In [1]:
import tensorflow as tf


In [2]:
# initializing two rank-2 tensors
x = tf.constant([1.,2.,3.])
y = tf.constant([2.,3.,4.])

print(f'x: {x}')
print(f'y: {y}')

x: [1. 2. 3.]
y: [2. 3. 4.]


In [5]:
print(x)
print(y)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [20]:
dot_product = tf.tensordot(x,y, axes = 1)
print(dot_product)


tf.Tensor(20.0, shape=(), dtype=float32)


#### Matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

In [21]:
x = tf.constant([[1., 2.],[3., 4.]])
y = tf.constant([[5., 6.],[7., 8.]])

print(x)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [23]:
# matrix multiplication
print(x @ y)

tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [24]:
# using matmul
tf.matmul(x,y)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>