# Henry Ezeanowi - 8900446

# LAB 8

### PART A - Using PyTorch

In [1]:
import torch

Calculate the dot product between two vectors each of length 3

In [2]:
# creating vectors v1 and v2 of length 3

v1  = torch.tensor([11,12,13])
v2 = torch.tensor([17,18,19])

v1, v2

(tensor([11, 12, 13]), tensor([17, 18, 19]))

In [3]:
# Calculate the dot product

dot_product = torch.dot(v1,v2)

print(dot_product)

tensor(650)


Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

In [4]:
# 2D matrices m1 and m2 of size (2,2)

m1 = torch.tensor([[2,3], [4,5]])
m2 = torch.tensor([[6,7], [8,9]])

m1, m2

(tensor([[2, 3],
         [4, 5]]),
 tensor([[6, 7],
         [8, 9]]))

In [5]:
# Matrix multiplication

matrix_multiplication = torch.matmul(m1,m2)

print(matrix_multiplication)

tensor([[36, 41],
        [64, 73]])


### PART B - Using Tensorflow

In [12]:
import tensorflow as tf

Calculate the dot product between the same vectors as above (re-define them in Tensorflow)

In [13]:
# Re-define the two vectors above as v_1 and v_2

v_1 = tf.constant([11,12,13])
v_2= tf.constant([17,18,19])

v_1, v_2

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 12, 13])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([17, 18, 19])>)

In [14]:
# Calculate the dot product

dot_prod = tf.tensordot(v_1, v_2, axes=1)

print(dot_prod)

tf.Tensor(650, shape=(), dtype=int32)


Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow)

In [15]:
# Re-define the two matrices above as m_1 and m_2

m_1 = tf.constant([[2,3], [4,5]])
m_2 = tf.constant([[6,7], [8,9]])

m_1, m_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[6, 7],
        [8, 9]])>)

In [16]:
# Matrix multiplication
matrix_mul = tf.matmul(m_1, m_2)

print(matrix_mul)

tf.Tensor(
[[36 41]
 [64 73]], shape=(2, 2), dtype=int32)
