# Part-I

In [1]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
# Load the Iris dataset
df = load_iris()

In [7]:
x=df.data

In [8]:
y=df.target

In [10]:
x


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [35]:
y.shape

(150,)

In [39]:
unique_counts_1 = np.unique(y, return_counts=True)

In [40]:
unique_counts_1

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

# Craetion of Label:

In [47]:
import numpy as np
#y_binary = np.where(y == 2, 1, 0)
y_binary = (y == 2).astype(int)

# Set Up of 2 Labels virginica and non virginica
Here I have changed the multiple unique values into binary numbers . Where 0 represents Non verginica and 1 reprsents Virginica.
By this filter the label value= '2' will be treated as 1(virginica) and rest of them will become 0 (Non virginica)

In [48]:
y_binary

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [49]:
unique_counts_1 = np.unique(y_binary, return_counts=True)
unique_counts_1

(array([0, 1]), array([100,  50], dtype=int64))

In [50]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y_binary, test_size=0.2, random_state=42)

In [51]:
# Train a logistic regression model
model = LogisticRegression()


In [52]:
model.fit(x_train, y_train)

LogisticRegression()

In [53]:
# Make predictions on the test set
y_pred = model.predict(x_test)

In [54]:
# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


In [55]:
# Calculate confusion matrix
conf = confusion_matrix(y_test, y_pred)


In [56]:
print("Confusion Matrix:",conf)


Confusion Matrix: [[19  0]
 [ 0 11]]


# Part-II 

# 1.  Insights
1. The accuracy score obtained from evaluating the model on the test data provides an overall measure of the model's performance. It represents the percentage of correctly predicted samples.

2. The logistic regression model's coefficients can give insight into the value of each feature in the classification process. Positive coefficients imply that increasing the associated characteristic value increases the likelihood of the sample being classed as "virginica," whereas negative coefficients indicate the reverse. We may learn which features have a greater effect on the categorization choice by studying these coefficients.
3. From the accuracy is **1** , we can see that there is overfitting.

# Wrong Prdeiction
From the accuracy score we can see that the accuracy is 100% but this is not true in real life. But according to the model there is no wrong prediction for any data point.

# Shared Properties
1. Analyse Feature Values: Examine the feature values of the misclassified cases to see if there are any parallels or trends. Examine the characteristics for specific ranges, combinations, or relationships that may contribute to misclassifications. Check to see if there are any examples with comparable petal lengths but differing sepal widths, or whether misclassifications are more common in a specific feature range.

2. Create visualisations for the misclassified cases and their feature distributions, such as scatter plots or histograms. Plotting the misclassified examples for each class individually might identify any overlapping regions or instances that are close to the decision border. These visualisations can help the model identify possible sources of misunderstanding.

# Performance


1. **Overfitting**: 
Overfitting occurs when a model performs exceptionally well on the training data but fails to generalize to new, unseen data. In this case, the model may have learned the training data too well, including noise and outliers, resulting in a perfect accuracy. However, it may struggle to perform well on new data. Words to describe overfitting include:

**Over-optimization**: The model has excessively optimized itself to the training data, leading to a perfect accuracy.

**Data memorization**: The model has essentially memorized the training data, including any inconsistencies or noise present.

**Lack of generalization**: The model may not generalize well to unseen data, making its perfect accuracy unreliable for real-world applications.

2. **Excellence**:
Alternatively, if the model achieves 100% accuracy and can still perform well on new, unseen data, it signifies excellence. In this case, the model might has successfully captured the underlying patterns and relationships in the data without overfitting. Words to describe excellence include:

**Exceptional**: The model's perfect accuracy demonstrates its exceptional performance and ability to capture the dataset's complexities.

**Outstanding**: The model's accuracy is outstanding, indicating its superior performance in accurately classifying instances.

