In [1]:
pip install tensorflow

In [1]:
import tensorflow as tf
import numpy as np

AttributeError: module 'numpy' has no attribute 'typeDict'

In [7]:
# Calculate the dot product between two vectors

In [8]:

vector1 = tf.constant([1, 2, 3], dtype=tf.float32)
vector2 = tf.constant([4, 5, 6], dtype=tf.float32)

In [16]:
v1 = np.asarray(vector1)

In [17]:
v1

array([1., 2., 3.], dtype=float32)

In [18]:
v2 = np.asarray(vector2)

In [19]:
v2

array([4., 5., 6.], dtype=float32)

In [20]:
dot_product = tf.tensordot(vector1, vector2, axes=1)
print("Dot Product:", dot_product.numpy())

Dot Product: 32.0


In [21]:
# Perform matrix multiplication


In [11]:
matrix1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
matrix2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

In [22]:
m1=np.asarray(matrix1)

In [23]:
m1

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [25]:
m2=np.asarray(matrix2)

In [26]:
m2

array([[5., 6.],
       [7., 8.]], dtype=float32)

In [27]:
matrix_product = tf.matmul(matrix1, matrix2)
print("Matrix Product:")
print(matrix_product.numpy())

Matrix Product:
[[19. 22.]
 [43. 50.]]
