# Lab 6 - Logistic Regression
## Sudhan Shrestha - 8889436

### 1. Using SciKit-Learn, train a logistic regression model on the Iris dataset. Use all four features. Define only 2 labels: virginica and non-virginica. See the logistic regression notebook presented in class for a demonstration on how to set up these labels (3 points).

In [169]:
# importing necessary libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score


In [170]:
# loading the irish dataset.
df_irish = load_iris(as_frame=True)

In [171]:
type(df_irish)

sklearn.utils._bunch.Bunch

In [172]:
list(df_irish)

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [173]:
# printing our all the keys of the dataset
for key in df_irish.keys():
    print(key, type(df_irish[key]))

data <class 'pandas.core.frame.DataFrame'>
target <class 'pandas.core.series.Series'>
frame <class 'pandas.core.frame.DataFrame'>
target_names <class 'numpy.ndarray'>
DESCR <class 'str'>
feature_names <class 'list'>
filename <class 'str'>
data_module <class 'str'>


In [174]:
df_irish.data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [175]:
df_irish.target.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [176]:
# shows the target names
df_irish.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [177]:
# Seperating the X and y features from the irish dataset
X = df_irish.data
y = df_irish.target_names[df_irish.target] == 'virginica'

In [178]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [179]:
y

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

#### Train Test Split

In [180]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#### Logistic Regression Model

In [181]:
log_model = LogisticRegression(random_state=42)
log_model.fit(X_train, y_train)

LogisticRegression(random_state=42)

#### Prediction

In [182]:
# Prediciting the values
y_pred = log_model.predict(X_test)
print("The predicted values on X_test: \n")
y_pred

The predicted values on X_test: 



array([False, False,  True, False, False, False, False,  True, False,
       False,  True, False, False, False, False, False,  True, False,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True, False, False])

### 2. Provide insights about the model prediction. This is an open-ended part. But you can look into questions such as in which data instances is the model wrong? are there any shared properties for these cases? and _how is the model doing, across a set of performance metrics such as accuracy and confusion metric. (3 points)

#### Cross-Validation :

In [183]:
# Perfoming cross-validation to check models perfomance across different folds

cv_score = cross_val_score(log_model, X_train, y_train, cv=5)
print("Cross-validation score: ", cv_score)
print("Average accuracy : ", np.mean(cv_score))

Cross-validation score:  [1.         0.95833333 0.875      0.95833333 0.95833333]
Average accuracy :  0.95


- After running cross-validation on the model we find that the model accuracy varies on each fold with perfect accuracy of 100% in the first fold and the minimum accuracy of about 87% on the third fold.
 - The average accuaracy of the model was found to be 95%.

### Accuracy:

In [184]:
accuracy = accuracy_score(y_test, y_pred)
print(f"The accuracy of the model : {accuracy}")

The accuracy of the model : 1.0


Our accuracy here is 1.0 which means that the model accuracy is perfect, and has no false predictions.

#### Confusion Metric:

In [185]:
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{conf_matrix}")

Confusion Matrix:
[[19  0]
 [ 0 11]]


From our confusion martix we can deduce that the model classified all 19 True Positive and all 11 True Negative and it dod not make any false prediciton i.e. there is no False Postivie or False Negative. Which means the model gave us the prefect accuaracy.

#### Precision and Recall :

In [186]:
prec_score = precision_score(y_test, y_pred)
rec_score = recall_score(y_test, y_pred)

print(f"Precision Score : {prec_score}")
print(f"Recall Score : {rec_score}")

Precision Score : 1.0
Recall Score : 1.0


- A precision score of 1.0 was obtained which means that all the instances  that were predicited as positive by the model were True Positive.
- A recall score of 1.0 means that the model correctly predicted all the positive instance of the dataset and ther were no False Negative.