# PyTorch

In [1]:
import torch

In [4]:
# Calculate the dot product between two vectors each of length 3

# Create 2 vectors in length of 3
v1 = torch.Tensor([10,12,55])
v2 = torch.Tensor([22,14,92])

# Calculate dot of vectors
dot_product = torch.dot(v1, v2)

# Print dot product
dot_product

tensor(5448.)

In [8]:
# Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

# Create 2-dimensional metrices
m1 = torch.tensor([[10,22], [27,54]])
m2 = torch.tensor([[14,11], [22,5]])

# Calculate matrix multiplication of matrices
mat_mul = torch.mm(m1, m2)

# Print multiplication
mat_mul

tensor([[ 624,  220],
        [1566,  567]])

# Tensorflow

In [1]:
import tensorflow as tf

In [4]:
# Calculate the dot product between the same vectors as above

# Create 2 vectors in length of 3
t_v1 = tf.constant([10,12,55])
t_v2 = tf.constant([22,14,92])

# Calculate dot of vectors
t_dot_product = tf.tensordot(t_v1, t_v2, axes=1)

# Print dot product
t_dot_product

<tf.Tensor: shape=(), dtype=int32, numpy=5448>

In [5]:
# Calculate the matrix multiplication of the same matrics as above

# Create 2-dimensional metrices
t_m1 = tf.constant([[10,22], [27,54]])
t_m2 = tf.constant([[14,11], [22,5]])

# Calculate matrix multiplication of matrices
t_mat_mul = tf.matmul(t_m1, t_m2)

# Print multiplication
t_mat_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 624,  220],
       [1566,  567]])>