<h1 align = "center"><B><U>Lab 8</U> - <U>A Dot product and a Matrix Multiplication in PyTorch and Tensorflow</U></B></h1>
<h3 align = "center"><B>Waseem Iqbal Shaikh(8902834)</B></h3>

<h3><B><U>Using Tensorflow</U>:</B></h3>


In [12]:
# Importing the neccessary packages:
import tensorflow as tf
import numpy as np

- Calculate the dot product between the same vectors as above (re-define them in Tensorflow) (1.5 points)


In [13]:
# Initializing two vectors of length 3:
x = tf.constant([1., 3., 5.])
y = tf.constant([2., 4., 6.])

# Displaying the type of variable x and y:
print("The vector 'x' is ",x)
print("The vector 'y' is ",y)

# Calculating the dot product between the two vectors 'x' and 'y':
dotProduct = tf.tensordot(x, y, axes = 1)
print("\nThe Dot Product of the two vectors 'x' and 'y' is", dotProduct)

The vector 'x' is  tf.Tensor([1. 3. 5.], shape=(3,), dtype=float32)
The vector 'y' is  tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)

The Dot Product of the two vectors 'x' and 'y' is tf.Tensor(44.0, shape=(), dtype=float32)


- Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)

In [14]:
# Initializing two 2-dimensional matrices each with a size of (2,2):
a = tf.constant([[1., 3.],[5., 7.]])
b = tf.constant([[2., 4.],[6., 8.]])

# Displaying the type of variable a and b:
print("The matrix 'a' is ",a)
print("The matrix 'b' is ",b)

# Calculate the matrix multiplication of two 2-dimensional matrices 'a' and 'b':
matrixMultiplication = tf.matmul(a,b)
print("\nThe result of multiplication between two 2-dimensional matrices 'a' and 'b', each with a size of (2,2) is:\n", matrixMultiplication)

The matrix 'a' is  tf.Tensor(
[[1. 3.]
 [5. 7.]], shape=(2, 2), dtype=float32)
The matrix 'b' is  tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)

The result of multiplication between two 2-dimensional matrices 'a' and 'b', each with a size of (2,2) is:
 tf.Tensor(
[[20. 28.]
 [52. 76.]], shape=(2, 2), dtype=float32)
