<h1 align = "center"><B><U>Lab 8</U> - <U>A Dot product and a Matrix Multiplication in PyTorch and Tensorflow</U></B></h1>
<h3 align = "center"><B>Waseem Iqbal Shaikh(8902834)</B></h3>


<h3><B><U>Using PyTorch</U>:</B><h3>


In [20]:
# Importing the neccessary packages:
import sys
import torch
import helpers as h

- Calculate the dot product between two vectors each of length 3 (1.5 points)


In [21]:
# Initializing two vectors of length 3:
x = torch.tensor([1., 3., 5.])
y = torch.tensor([2., 4., 6.])

# Displaying the type of variable x and y:
h.print_tensor_info(x)
print("\n")
h.print_tensor_info(y)

# Calculating the dot product between the two vectors 'x' and 'y':
dotProduct = x.dot(y)
print("\nThe Dot Product of the two vectors 'x' and 'y' is", dotProduct)

tensor([1., 3., 5.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (3,)


tensor([2., 4., 6.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (3,)

The Dot Product of the two vectors 'x' and 'y' is tensor(44.)


- Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) (1.5 points)

In [22]:
# Initializing two 2-dimensional matrices each with a size of (2,2):
a = torch.tensor([[1., 3.],[5., 7.]])
b = torch.tensor([[2., 4.],[6., 8.]])

# Displaying the type of variable a and b:
h.print_tensor_info(a)
print("\n")
h.print_tensor_info(b)

# Calculate the matrix multiplication of two 2-dimensional matrices 'a' and 'b':
matrixMultiplication = a.matmul(b)
print("\nThe result of multiplication between two 2-dimensional matrices 'a' and 'b', each with a size of (2,2) is:\n", matrixMultiplication)

tensor([[1., 3.],
        [5., 7.]])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    2
Shape        (2, 2)


tensor([[2., 4.],
        [6., 8.]])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    2
Shape        (2, 2)

The result of multiplication between two 2-dimensional matrices 'a' and 'b', each with a size of (2,2) is:
 tensor([[20., 28.],
        [52., 76.]])
