# Foundation Machine Learning Frameworks
### Zohair Mubasheer Ahmed
### Student Id - 8897082
#### Lab Submission 8

In [4]:
import tensorflow as tf

In [5]:
a = tf.constant([1., 3., 5.])
b = tf.constant([2., 4., 6.])

dotProduct = tf.tensordot(a, b, axes = 1)
print("The Dot Product of the two vectors 'x' and 'y' is")
dotProduct

The Dot Product of the two vectors 'x' and 'y' is


<tf.Tensor: shape=(), dtype=float32, numpy=44.0>

In [6]:
# Initializing two 2-D matrices
x = tf.constant([[1., 3.],[5., 7.]])
y = tf.constant([[2., 4.],[6., 8.]])

# Printing the Matrices
print("The matrix x is ",x)
print("The matrix y is ",y)

# Matrix multiplication
matMultiplication = tf.matmul(x,y)
print("\nThe result of multiplication is:\n")
matMultiplication

The matrix 'x' is  tf.Tensor(
[[1. 3.]
 [5. 7.]], shape=(2, 2), dtype=float32)
The matrix 'y' is  tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] ndims must be == 2: 1 [Op:MatMul]