# Foundation Machine Learning Frameworks
### Zohair Mubasheer Ahmed
### Student Id - 8897082
#### Lab Submission 8 (PyTorch)

In [1]:
import torch
import helpers as h
import sys

- Performing Dot Product of two vectors

In [2]:
# Initializing two vectors
a = torch.tensor([1., 3., 5.])
b = torch.tensor([2., 4., 6.])

# Displaying the vectors
h.print_tensor_info(a)
print("\n")
h.print_tensor_info(b)

# Calculating the dot product
dotProduct = a.dot(b)
print("\nThe Dot Product is")
dotProduct

tensor([1., 3., 5.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (3,)


tensor([2., 4., 6.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (3,)

The Dot Product of the two vectors 'x' and 'y' is tensor(44.)


- Performing the Dot product of two Matrices

In [3]:
# Initializing two 2D matrices
x = torch.tensor([[1., 3.],[5., 7.]])
y = torch.tensor([[2., 4.],[6., 8.]])

# Displaying the Matrices
h.print_tensor_info(x)
print("\n")
h.print_tensor_info(y)

# Multiplying the Matrices
matrixMultiplication = x.matmul(y)
print("\nThe result of multiplication is:\n")
matrixMultiplication

tensor([[1., 3.],
        [5., 7.]])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    2
Shape        (2, 2)


tensor([[2., 4.],
        [6., 8.]])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    2
Shape        (2, 2)

The result of multiplication between two 2-dimensional matrices 'a' and 'b', each with a size of (2,2) is:
 tensor([[20., 28.],
        [52., 76.]])
