### Dot Product using pytorch 

In [2]:

import torch
import numpy as np
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])
print(vector1)
print(vector2)
print(torch.dot(vector1,vector2))



tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(32)


### Matrix Multiplication of 2-dimensional Matrices using pytorch

In [4]:

matrix1 = torch.tensor([[1,2],[3,4]])
matrix2 = torch.tensor([[5,6],[7,8]])
print(matrix1)
print(matrix2)
print(torch.matmul(matrix1,matrix2))

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[19, 22],
        [43, 50]])


### Dot product using tensorflow

In [4]:

import tensorflow as tf
vector1 = tf.constant([1,2,3])
vector2 = tf.constant([4,5,6])
print(vector1)
print(vector2)
print(tf.tensordot(vector1,vector2,axes=1))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)


### Matrix Multiplication using Tensorflow

In [3]:

matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[5,6],[7,8]])
print(matrix1)
print(matrix2)
print(tf.matmul(matrix1,matrix2))


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
