**SABIHA BEGUM MOHAMAD GHOUSE**
**(8896658)**

***Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow***

Using PyTorch:
- Calculate the dot product between two vectors each of length 3 (1.5 points)


In [2]:
#import packages
import torch

In [3]:

# Defining the two vectors
pt_vect1 = torch.tensor([3, 6, 9])
pt_vect2 = torch.tensor([2, 4, 8])

# Calculate the dot product 
dot_product = torch.dot(pt_vect1, pt_vect2)

# Print the result
print("Dot Product of pt_vect1 and pt_vect2:", dot_product.item())


Dot Product of pt_vect1 and pt_vect2: 102


- Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

In [4]:
# Defining the two matrices
matrix_1 = torch.tensor([[2, 2], [4, 4]])
matrix_2 = torch.tensor([[6, 6], [8, 8]])

# Perform matrix multiplication using matmul
result = torch.matmul(matrix_1, matrix_2)

# Print the result
print("Matrix Multiplication :")
print(result)


Matrix Multiplication :
tensor([[28, 28],
        [56, 56]])


We then use the torch.matmul() function to perform matrix multiplication between the two matrices 

Matrix multiplication can be done by another method Using the @ operator

In [9]:
# Defining the two matrices
matrix_3 = torch.tensor([[2, 2], [4, 4]])
matrix_4 = torch.tensor([[6, 6], [8, 8]])

# Perform matrix multiplication using @
result_2 = matrix_3 @ matrix_4

# Print the result
print("Matrix Multiplication Result:")
print(result_2)


Matrix Multiplication Result:
tensor([[28, 28],
        [56, 56]])


Using Tensorflow:
- Calculate the dot product between the same vectors as above (re-define them in Tensorflow)

In [12]:
#import package
import tensorflow as tf

In [14]:
# Define the two vectors
tf_vector1 = tf.constant([1, 2, 3])
tf_vector2 = tf.constant([4, 5, 6])

# Calculate the dot product
dot_product = tf.tensordot(tf_vector1, tf_vector2, axes=1)

# Print the result
print("Dot Product:", dot_product)

Dot Product: tf.Tensor(32, shape=(), dtype=int32)


- Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow)

In [19]:
# Define the matrices

matrix_1 = tf.constant([[4, 2], [7, 4]])
matrix_2 = tf.constant([[2, 6], [9, 8]])

# Calculate the matrix multiplication using tf.matmul()
result = tf.matmul(matrix_1, matrix_2)

print("Matrix multiplication:")
print(result)

Matrix multiplication:
tf.Tensor(
[[26 40]
 [50 74]], shape=(2, 2), dtype=int32)


We then use the tf.matmul() function to perform matrix multiplication between the two matrices 

Matrix multiplication can be done by another method Using the @ operator

In [18]:
# Define the matrices
matrix_3 = tf.constant([[4, 2], [7, 4]])
matrix_4 = tf.constant([[2, 6], [9, 8]])

# Calculate the matrix multiplication using the @ operator
result_2 = matrix_3 @ matrix_4

print("Matrix multiplication:")
print(result_2)

Matrix multiplication:
tf.Tensor(
[[26 40]
 [50 74]], shape=(2, 2), dtype=int32)
